# Generated by Django 5.1.1 on 2024-10-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('warehouse_worker', 'Warehouse Worker'), ('logistics_specialist', 'Logistics Specialist'), ('project_handler', 'Project Handler')], max_length=50),
        ),
    ]
