# Generated by Django 5.1.2 on 2024-10-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('warehouse_worker', 'Warehouse Worker'), ('logistics_specialist', 'Logistics Specialist'), ('project_handler', 'Project Handler')], max_length=50),
        ),
    ]
