# Generated by Django 5.1.2 on 2024-11-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('WARHOUSE_WORKER', 'Warehouse Worker'), ('LOGISTICS_SPECIALIST', 'Logistics Specialist'), ('PROJECT_HANDLER', 'Project Handler')], max_length=50),
        ),
    ]
