# Generated by Django 5.1.3 on 2024-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('WAREHOUSE_WORKER', 'Warehouse Worker'), ('LOGISTICS_SPECIALIST', 'Logistics Specialist'), ('PROJECT_HANDLER', 'Project Handler')], max_length=50),
        ),
    ]
