# Generated by Django 5.1.1 on 2024-10-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Scheduled', 'Scheduled')], default='Pending', max_length=50),
        ),
    ]
