# Generated by Django 5.1.2 on 2024-11-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_distribution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SCHEDULED', 'Scheduled')], default='Pending', max_length=50),
        ),
    ]
