# Generated by Django 5.1.3 on 2024-11-19 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_asset_thumbnail'),
        ('distribution', '0004_alter_distribution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionproduct',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_products', to='distribution.distribution'),
        ),
        migrations.CreateModel(
            name='DistributionAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_assets', to='distribution.distribution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
