# Generated by Django 5.1.3 on 2024-11-19 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_alter_distributionproduct_distribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionasset',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='distribution.distribution'),
        ),
        migrations.AlterField(
            model_name='distributionproduct',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='distribution.distribution'),
        ),
    ]
