# Generated by Django 5.1.3 on 2024-12-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_alter_distributionasset_distribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionasset',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionproduct',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
