# Generated by Django 5.1.3 on 2024-12-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_distributionasset_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='ba_reference_number',
            field=models.CharField(blank=True, help_text='Reference number for allocations.', max_length=100, null=True),
        ),
    ]
