# Generated by Django 5.1.3 on 2024-12-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_distribution_ba_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='dist_id',
        ),
        migrations.AlterField(
            model_name='distribution',
            name='ba_reference_number',
            field=models.CharField(blank=True, help_text='Reference number for allocations.', max_length=100, null=True, unique=True),
        ),
    ]
