# Generated by Django 5.1.3 on 2024-12-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0009_remove_distribution_dist_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionasset',
            name='expiration',
        ),
    ]
