# Generated by Django 5.1.3 on 2024-12-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0010_remove_distributionasset_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='ba_reference_number',
            field=models.CharField(help_text='Reference number for allocations.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='distributionproduct',
            name='expiration',
            field=models.DateTimeField(),
        ),
    ]
