# Generated by Django 5.1.1 on 2024-09-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
