# Generated by Django 5.1.2 on 2024-11-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
