# Generated by Django 5.1.2 on 2024-11-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
