# Generated by Django 5.1.3 on 2024-11-21 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_asset_thumbnail'),
        ('product', '0006_alter_product_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
