# Generated by Django 5.1.3 on 2024-11-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_asset_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
