# Generated by Django 5.1.3 on 2024-12-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_asset_ba_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
