# Generated by Django 5.1.1 on 2024-10-21 15:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0002_distribution_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('IN PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=50)),
                ('type', models.CharField(choices=[('EXPORT', 'Export'), ('IMPORT', 'Import')], max_length=50)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='distribution.distribution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
