# Generated by Django 5.1.1 on 2024-10-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('CHECKED_IN', 'Checked In'), ('STOCKED', 'Stocked'), ('SHELVED', 'Shelved'), ('PICKED', 'Picked'), ('PACKED', 'Packed'), ('LOADED', 'Loaded'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=50),
        ),
    ]
