# Generated by Django 5.1.3 on 2024-11-21 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('task', '0005_remove_task_employee_task_warehouse_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='warehouse_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
