# Generated by Django 5.1.3 on 2024-11-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_alter_distributionasset_distribution_and_more'),
        ('employee', '0001_initial'),
        ('task', '0006_alter_task_warehouse_person'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('warehouse_person', 'distribution')},
        ),
    ]
